# Generated by Django 3.1.2 on 2021-09-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdivisions', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level_in_subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivisions.level', verbose_name='Уровень в подразделении'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_at_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subdivisions.positionatwork', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivisions.subdivision', verbose_name='Подразделение'),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='PositionAtWork',
        ),
        migrations.DeleteModel(
            name='Subdivision',
        ),
    ]
